name: ChatApp

on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: 
            echo "WORKS!"

        env:
            REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
            REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
            REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
            REACT_APP_STPRAGE_BUCKET: ${{ secrets.REACT_APP_STPRAGE_BUCKET }}
            REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
            REACT_APP_APP_ID: ${{ secrets.REACT_APP_APP_ID }}
            REACT_APP_MEASUREMENT_ID: ${{ secrets.REACT_APP_MEASUREMENT_ID }}
